version: "3.9"

services:
  api:
    build: .
    container_name: token-aware-rate-limiter
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    env_file: 
      - .env
    depends_on: 
      - redis 
      - db
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/token_aware_rate_limiter_db

  redis: 
    image: redis:7
    container_name: redis 
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: token_aware_rate_limiter_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./db/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

volumes:
  pgdata:
